/* This file was generated by syncqt. */
#ifndef QT_QTWEBVIEW_VERSION_H
#define QT_QTWEBVIEW_VERSION_H

#define QTWEBVIEW_VERSION_STR "5.12.9"

#define QTWEBVIEW_VERSION 0x050C09

#endif // QT_QTWEBVIEW_VERSION_H
