/* This file was generated by syncqt. */
#ifndef QT_QTGAMEPAD_VERSION_H
#define QT_QTGAMEPAD_VERSION_H

#define QTGAMEPAD_VERSION_STR "5.12.9"

#define QTGAMEPAD_VERSION 0x050C09

#endif // QT_QTGAMEPAD_VERSION_H
