/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "5.12.9"

#define QTCHARTS_VERSION 0x050C09

#endif // QT_QTCHARTS_VERSION_H
