/* This file was generated by syncqt. */
#ifndef QT_QT3DRENDER_VERSION_H
#define QT_QT3DRENDER_VERSION_H

#define QT3DRENDER_VERSION_STR "5.12.9"

#define QT3DRENDER_VERSION 0x050C09

#endif // QT_QT3DRENDER_VERSION_H
